In [110]:
NICKNAME = "ariunaK"

In [2]:
#1
import numpy as np

In [112]:
#2
print(np.__version__)
np.show_config()

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,S

In [113]:
#3
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [114]:
#4
x = np.zeros((10,5))
print("%d bytes" % (x.size * x.itemsize))

400 bytes


In [115]:
#5
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [116]:
#6
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [117]:
#7
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [118]:
#8
x = x[::-1]
x

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [119]:
#9
A = np.arange(9).reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [120]:
#10
p = np.nonzero([1, 2, 0 ,0 , 4, 0])
p

(array([0, 1, 4], dtype=int64),)

In [121]:
#11
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [122]:
#12
B = np.random.random((3,3,3))
B

array([[[0.83275584, 0.78976641, 0.77450015],
        [0.38864605, 0.90381741, 0.22089779],
        [0.04216755, 0.37907782, 0.14614947]],

       [[0.79579127, 0.47648052, 0.45134971],
        [0.09981786, 0.55204211, 0.57835112],
        [0.42418048, 0.11458849, 0.49640983]],

       [[0.8691766 , 0.3417329 , 0.50515117],
        [0.68328329, 0.76816864, 0.93893446],
        [0.02332568, 0.19651161, 0.04886783]]])

In [123]:
#13
A = np.random.random((10,10))
a1 = A.min()
a2 = A.max()
a1, a2

(0.007578754325831105, 0.9892584592362386)

In [124]:
#14
x = np.random.random(30)
y = x.mean()
y

0.5133875729281314

In [125]:
#15
x = np.ones((5,5))
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [126]:
#16
x = np.ones((5,5))
x = np.pad(x, 1, constant_values=0)
x

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [127]:
#17
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [128]:
#18
A = np.diag(1 + np.arange(4), -1)
A

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [129]:
#19
def checkerboard(w, b):

    # YOUR CODE HERE
    m = np.array(([w, b]*4 + [b, w]*4)*4).reshape((8,8))
    return m

p = checkerboard(0, 1)
print(p)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [130]:
#20
np.unravel_index(99,(6,7,8))

(1, 5, 3)

In [131]:
#21
np.tile(np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [132]:
#22
A = np.random.random((5, 5))
norms = np.linalg.norm(A, axis=1)
A1 = A / norms
A1

array([[0.55549228, 0.47658118, 0.3023664 , 0.04607759, 0.56689887],
       [0.42641446, 0.23311901, 0.60154825, 0.39109625, 0.35392842],
       [0.3389316 , 0.00884284, 0.0267122 , 0.54559307, 0.60708841],
       [0.17433427, 0.36073129, 0.5285422 , 0.39842862, 0.4307081 ],
       [0.71430207, 0.22011643, 0.25295574, 0.97513201, 0.1815362 ]])

In [133]:
#23
color = np.dtype([("r", np.ubyte), ("g", np.ubyte), ("b", np.ubyte), ("a", np.ubyte)])

In [134]:
#24
a = np.random.random((5, 3))
b = np.random.random((3, 2))
c = a @ b
c

array([[0.4650354 , 0.14454014],
       [0.68346805, 0.64767543],
       [0.77239885, 0.70252975],
       [0.75777149, 0.67012471],
       [0.5715005 , 0.28211613]])

In [135]:
#25
x = np.random.random(18)
for i in range(4, 8):
    x[i] *= -1
x

array([ 0.23647602,  0.40714158,  0.05765764,  0.85220804, -0.12731083,
       -0.98447298, -0.43008799, -0.43866203,  0.94359443,  0.4050001 ,
        0.2071515 ,  0.33313777,  0.78909887,  0.69181091,  0.13684822,
        0.42271553,  0.217165  ,  0.64956498])

In [136]:
#26
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [137]:
#27
Z = np.arange(4)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z #не это

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [138]:
#28
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

In [139]:
#30
x = np.random.randint(0, 13, 7)
y = np.random.randint(0, 13, 7)
z = np.intersect1d(x, y)
z


array([1, 7])

In [140]:
#31
np.seterr(all="ignore")

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

In [141]:
err = np.seterr(all="ignore")
_ = np.seterr(**err)


In [142]:
#32
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [143]:
#33
y = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tod = np.datetime64('today', 'D')
tom = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(y, tod, tom)

2022-10-29 2022-10-30 2022-10-31


In [146]:
#34
J = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(J)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [152]:
#35
A = np.ones(4)*4
B = np.ones(4)
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-10., -10., -10., -10.])

In [6]:
#36
x = np.random.uniform(0, 24, size=10)

print(x - x % 1)
print(x // 1)
print(np.floor(x))
print(np.trunc(x))

[16. 18.  7.  6. 16. 17. 22. 22. 19. 19.]
[16. 18.  7.  6. 16. 17. 22. 22. 19. 19.]
[16. 18.  7.  6. 16. 17. 22. 22. 19. 19.]
[16. 18.  7.  6. 16. 17. 22. 22. 19. 19.]


In [8]:
#37
x = np.arange(5)
x0 = x
for i in range(4):
    x = np.vstack((x, x0)) 
x

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [21]:
#38
def gen():
    for x in range(10):
        yield x
x = np.fromiter(gen(),dtype=float,count=-1)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [22]:
#39
x = np.random.uniform(0.1, 1, 10)
x

array([0.81488899, 0.57769925, 0.13425723, 0.12472635, 0.33203229,
       0.59464807, 0.3774728 , 0.38743872, 0.72777677, 0.40051227])

In [23]:
#40
x = np.random.random(10)
x.sort()
x

array([0.22637034, 0.35066209, 0.44012947, 0.48509695, 0.50511818,
       0.517834  , 0.59355655, 0.61509386, 0.89354488, 0.98340901])

In [24]:
#41
x = np.arange(10)
np.add.reduce(x)

45

In [26]:
#42
a = np.random.random(10)
b = np.random.random(10)
np.allclose(a, b)

False

In [28]:
#43
a = np.zeros(10)
a.flags.writeable = False

In [29]:
#44
def cartesian_to_polar(c):
    p = np.array([[np.sqrt(x**2 + y**2), np.arctan2(y, x)] for x, y in c])
    return p
x = np.random.random((10,2))
cartesian_to_polar(x)

array([[1.26269681, 0.87958866],
       [0.80592981, 0.03516802],
       [1.01060549, 0.77105509],
       [0.89056114, 0.58330646],
       [0.99874946, 0.43752975],
       [0.92979437, 0.78137971],
       [0.94218837, 0.94157779],
       [0.91694823, 0.43511776],
       [0.99743849, 1.35714908],
       [0.63681103, 1.40280875]])

In [38]:
#45
x = np.random.random(10)
print(x)
x[x.argmax()] = 0
print(x)

[0.59492189 0.6975812  0.19804932 0.02371615 0.85910806 0.97897036
 0.29120219 0.47319597 0.08328941 0.31567845]
[0.59492189 0.6975812  0.19804932 0.02371615 0.85910806 0.
 0.29120219 0.47319597 0.08328941 0.31567845]


In [40]:
#46
z = np.zeros((5, 5), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [64]:
#47
x = np.random.uniform(0.1, 10, 4)
y = np.random.uniform(0.1, 10, 4)
c = 1.0 / (x.reshape((-1, 1)) - y)
c


array([[-0.63545976, -0.50304686,  0.4524624 ,  0.14482016],
       [-2.13713787, -1.13360928,  0.30157937,  0.12483047],
       [-0.27866699, -0.24982917,  5.12086149,  0.2044878 ],
       [-0.11286639, -0.10782536, -0.19699614, -2.62292332]])

In [53]:
#48
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


In [59]:
#49
np.set_printoptions(threshold = float("inf"))
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [62]:
#50
x = np.arange(241)
v = np.random.uniform(0,100)
i = (np.abs(x-v)).argmin()
print(x[i])

65


In [63]:
#51
a = np.zeros(10, [ ('position', [ ('x', float, 1), ('y', float, 1)]),
                   ('color',    [ ('r', float, 1), ('g', float, 1), ('b', float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\HP\AppData\Local\Temp\ipykernel_17612\724186763.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = np.zeros(10, [ ('position', [ ('x', float, 1), ('y', float, 1)]),


In [67]:
#52
import scipy.spatial as sp

x = np.random.random((10, 2))
D = sp.distance.cdist(x, x)
print(D)

[[0.         0.58603865 0.56948432 0.78027692 1.14434184 0.80403984
  0.69171968 0.69819233 1.13364883 0.43590099]
 [0.58603865 0.         0.58092037 0.20293358 0.79013653 0.91711366
  0.21557722 0.30631079 0.7855159  0.29747224]
 [0.56948432 0.58092037 0.         0.6542151  0.64215864 0.33676965
  0.47967221 0.39644024 0.62892328 0.29722974]
 [0.78027692 0.20293358 0.6542151  0.         0.67412265 0.97485189
  0.17717743 0.27843478 0.67278731 0.42380946]
 [1.14434184 0.79013653 0.64215864 0.67412265 0.         0.7530112
  0.5746178  0.49768906 0.01458681 0.72010634]
 [0.80403984 0.91711366 0.33676965 0.97485189 0.7530112  0.
  0.79771171 0.7018824  0.73843217 0.63240259]
 [0.69171968 0.21557722 0.47967221 0.17717743 0.5746178  0.79771171
  0.         0.10654924 0.56993947 0.28223182]
 [0.69819233 0.30631079 0.39644024 0.27843478 0.49768906 0.7018824
  0.10654924 0.         0.49116951 0.26468156]
 [1.13364883 0.7855159  0.62892328 0.67278731 0.01458681 0.73843217
  0.56993947 0.4911695

In [74]:
#53
x = np.arange(10, dtype=np.float32)
x = x.astype(np.int32, copy=False)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [75]:
#54
x = np.genfromtxt('1.txt', delimiter=',')  
print(x)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


In [79]:
#55
x = np.arange(9).reshape(3,3)
for i, value in np.ndenumerate(x):
    print(i, value)
for i in np.ndindex(x.shape):
    print(i, x[i])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [80]:
#56
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
D = np.sqrt(X**2 + Y**2)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / (2.0*sigma**2) ))
print (G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [82]:
#57
p = 3
A = np.zeros((5,5))
np.put(A, np.random.choice(range(5*5), p, replace=False),1)
print(A)

[[0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [83]:
#58
x = np.random.rand(5, 10)
y = x - x.mean(axis=1, keepdims=True)
y = x - x.mean(axis=1).reshape(-1, 1)

print(y)

[[-0.52523246  0.15242029 -0.00661557  0.3045188  -0.43251445  0.21548463
  -0.08743479  0.08724413  0.20082997  0.09129945]
 [-0.07908413  0.29194639 -0.56111044  0.14314172 -0.0551773   0.17070731
   0.17703529 -0.42108487  0.07362992  0.25999611]
 [ 0.43669065 -0.10944969  0.248245   -0.42912775  0.11652465  0.21185095
  -0.37299995  0.00104713  0.37036507 -0.47314607]
 [-0.40421702  0.16781279  0.1560723  -0.40056618 -0.29667505  0.43145984
  -0.04732937  0.26807938  0.15225325 -0.02688995]
 [-0.06018241  0.23145786 -0.02838948 -0.02091023 -0.48595745  0.29946286
   0.42373747  0.3519435  -0.28133928 -0.42982284]]


In [86]:
#59
n = 2
a = np.random.randint(0, 10, (3, 4))
print(a)
print(a [a[:, n].argsort() ])

[[1 7 0 3]
 [8 6 4 1]
 [0 6 1 5]]
[[1 7 0 3]
 [0 6 1 5]
 [8 6 4 1]]


In [95]:
#60
a = np.random.randint(0, 2, (3, 4))

print((~a.any(axis = 0)).any())


True


In [98]:
#61
x = np.random.uniform(0, 10, 10)
a = 6
m = x.flat[np.abs(x - a).argmin()]
print(m)

6.082058921159433


In [99]:
#62
A = np.arange(3).reshape(3, 1)
B = np.arange(3).reshape(1, 3)
it = np.nditer([A, B, None])
for x, y, z in it:
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [101]:
#63
class NameArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

a = NameArray(np.arange(10), "range_10")
print(a.name)

range_10


In [103]:
#64
x = np.ones(10)
y = np.random.randint(0, 10, 20)
np.add.at(x, y, 1)
print(x)


[4. 2. 1. 3. 2. 3. 2. 5. 5. 3.]


In [125]:
#65
X = np.arange(6)
I = np.random.randint(0, 10, 6)
F = np.bincount(I, X)
print(F)

[0. 0. 0. 0. 1. 0. 0. 9. 0. 5.]


In [126]:
#66
w, h = 16, 16
I = np.random.randint(0, 2, (h, w, 3)).astype(np.ubyte)
F = I[..., 0] * 256 * 256 + I[..., 1] * 256 + I[..., 2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


In [127]:
#67
A = np.random.randint(0, 10, (3, 4, 3, 4))
sum = A.sum(axis=(-2, -1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[63 59 61 44]
 [58 50 55 62]
 [68 57 61 73]]
[[63 59 61 44]
 [58 50 55 62]
 [68 57 61 73]]


In [ ]:
#68